added some changes
asavienko/todo pull request #1
Opened 2019-05-04 18:23 UTC by asavienko

2019-05-04 19:23 UTC, byuzyfyshyn requested changes

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/App.css
> +  transition: all .3s;
add mixin for transition

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/App.css
>  @keyframes App-logo-spin {
remove this part code

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/App.css
> +  transition: all .3s;
or better move to styled component all this file

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/InputItem.js
> +    this.props.addTodoItem(this.state.todoInput);
```suggestion
    const {todoInput} = this.state;
    this.props.addTodoItem(todoInput);
```

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/InputItem.js
> +    this.setState({todoInput: e.target.value})
```suggestion
    const todoInput = e.target.value;
    this.setState({todoInput});
```

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/Todo.js
> +  <div style={{textAlign: 'center'}}>
remove inline style

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/Todo.js
> +        {/*<ListControl/>*/}
remove comment

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/Todo.js
> +          style={{
remove inline style

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/Todo.js
> +          renderItem={item => (<TodoItem
(item) || item in all places with only one parameter

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/TodoItem.js
> +import styled from "styled-components";
```suggestion
import styled, {css} from "styled-components";
```

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/TodoItem.js
> +      text-decoration: ${({completedStyle}) => completedStyle ? "line-through" : "none"};
${(props)=> props.completedStyle ? css`text-decoration: line-through; color: #999` : css`text-decoration: none `}

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/TodoItem.js
> +  toggleInput = (item) => {
```suggestion
  toggleInput = ({todoItem: editInputValue, todoItemId: editInputId}) => {
```

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/TodoItem.js
> +      editInputValue: item.todoItem,
```suggestion
      editInputValue,
```

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/TodoItem.js
> +      editInputId: item.todoItemId,
```suggestion
      editInputId,
```

2019-05-04 19:23 UTC, byuzyfyshyn commented on src/TodoItem.js
> +    this.props.editTodoItem(
const {editInputValue, editInputId} = this.state;

2019-05-04 19:23 UTC, Nerosman commented on src/TodoItem.js
> +          onClick={() => this.deleteItem(item.todoItemId)}
onClick={this.deleteItem}

2019-05-04 19:23 UTC, Nerosman commented on src/TodoItem.js
> +    this.props.deleteTodoItem(id)
const {todoItemId} = this.props.item

2019-05-04 19:23 UTC, Nerosman commented on src/TodoItem.js
> +  deleteItem = (id) => {
```suggestion
  deleteItem = () => {
```

2019-05-04 19:23 UTC, Nerosman commented on src/TodoItem.js
> +    this.props.deleteTodoItem(id)
```suggestion
    this.props.deleteTodoItem(todoItemId)
```

2019-05-04 19:23 UTC, Nerosman commented on src/TodoItem.js
> +          onChange={(e) => this.switchShowCheckbox(e, item.todoItemId)}
same

2019-05-04 19:23 UTC, Nerosman commented on src/TodoItem.js
> +const mapDispatchToProps = (dispatch) => {
```suggestion
const mapDispatchToProps = (dispatch, {item : {todoItemId, todoItemActive}}) => {
```

2019-05-04 19:23 UTC, Nerosman commented on src/TodoItem.js
> +    deleteTodoItem: (id) => {
```suggestion
    deleteTodoItem: () => {
```

2019-05-04 19:23 UTC, Nerosman commented on src/TodoItem.js
> +      dispatch(deleteTodoItem(id))
```suggestion
      dispatch(deleteTodoItem(todoItemId))
```

2019-05-04 19:23 UTC, Nerosman commented on src/actions/todoActions.js
> +  const {todoReducer} = state;
```suggestion
  const {todoReducer: {todoList}} = state;
```

2019-05-04 19:23 UTC, Nerosman commented on src/actions/todoActions.js
> +  const newTodoList = todoReducer.todoList.concat([{
### 
```suggestion
  const newTodoList = todoList.concat([{
```

2019-05-09 15:43 UTC, asavienko commented on src/TodoItem.js
> +const mapDispatchToProps = (dispatch) => {
Function receives argument todoItemActive form state. Doesn't from porps.

2019-05-11 17:09 UTC, byuzyfyshyn requested changes

2019-05-11 17:09 UTC, byuzyfyshyn commented on src/InputItem.js
> +    console.log(allValueChecked)
remove console.log()

2019-05-11 17:09 UTC, byuzyfyshyn commented on src/InputItem.js
> +      todoInput: "",
rename todoInput to todoInputValue

2019-05-11 17:09 UTC, byuzyfyshyn commented on src/InputItem.js
> +const StyledWrapper = styled.div`
rename StyledWrapper to StyledContainer

2019-05-11 17:09 UTC, byuzyfyshyn commented on src/InputItem.js
> +      ({todoItemActive}) => todoItemActive === true
item => item.todoItemActive

2019-05-11 17:09 UTC, byuzyfyshyn commented on src/InputItem.js
> +        but I need to do switchCompletedAll function when I click to child checkboxes in the list.
remove comment

2019-05-11 17:09 UTC, byuzyfyshyn commented on src/TodoItem.js
> +          onClick={() => this.toggleInput(item)}
move item to function

2019-05-11 17:09 UTC, byuzyfyshyn commented on src/TodoItem.js
> +    editTodoItem: (todoItem) => {
rename todoItem to todoItemValue

2022-12-14 18:43 UTC, merged